### ISSUE TITLE
in 05_loops.py match of user's guess and answer should be first

### ISSUE THREAD

**Issue by winonatong** [code-workshops/python-exercises#4]
When the correct number is guessed on the 3rd try, the program says "too many tries" instead of "YOU WIN" because the check for the number of tries precedes the check for a correct answer in the if/elif block

**Comment by winonatong** [comment]
```
    if tries >= 3:
        print "Too many tries! The answer is: ", answer
        GAME_ON = False
    elif YOUR_COMPARISON_HERE:
        print "Too high!"
        tries += 1
    elif YOUR_COMPARISON_HERE:
        print "Too low!"
        # Increment the number of tries below
        tries += 1
    else:
        print "CORRECT! YOU WIN!"
        break
```

**Comment by mosdevly** [comment]
Thanks @winonatong Actually looks like 3 issues:

1. `tries` is currently started at 1. It should start at 0
2. There should be 2 if statements: one that checks answers AND one that checks `tries`. They should not be part of the same condition check
3. The condition for `tries` should indeed be last.

I get an F for thorough testing!

I'll fix this ASAP. Also I forgot I made a student branch in the repo which gave an alternative introduction to loops. However I don't think I finished the related exercise for that one. 

Thanks for this. Please continue to post feedback here and we'll make these lessons perfect together :)
